### ISSUE TITLE
No prestige bonus for disrupt in philippines

### ISSUE THREAD

**Issue by justinkwaugh** [sellmerfud/awakening#1]
I had a game where I had 2 troops in the philippines with a hard posture as I recall troops were deployed there because of abu sayyaf.  A single cell was present and my subsequent disrupts to flip it to active and then remove it and the resulting cadre did not increase US prestige.

**Comment by justinkwaugh** [comment]
To follow up I looked at the code and it is because you are assuming that all non-muslim countries will not result in prestige increase (because you can't normally deploy troops to them) but this is a special case due to abu sayyaf, and the disrupt rules definitely do not restrict the +1 bonus to non-muslim countries, so perhaps that assumption should just be removed, as checking for 2+ troops should be correct in all cases.

**Comment by sellmerfud** [comment]
Fixed in release 2.11
Not correctly affects 2 cells and bumps prestige if two or more troops are present.
