### ISSUE TITLE
Disable "Exit game after victory" Bug

### ISSUE THREAD

**Issue by GameTime14** [sellmerfud/awakening#10]
Hi Curt,

Today I attempted a Grand Campaign with both expansions using the latest v4.12

Unfortunately the program crashes/quits as soon as my first Victory condition was met.

I checked the save game folder and the following description file is generated; "Game Over - US automatic victory!"

In previous versions you could continue to play through this as to experience the entire complete game.
(I first used your app 3 years ago and this was not a problem)

Searching the Save Game Files I found this;

"Options:",
"----------------------------------------------------",
"Exit game after victory: yes",
""
I tried changing the "yes" to "no" on all files, and even removed the line entirely, but the game continues to exit out after the first victory condition is met.

I would love to be able to play the entire grand campaign using your app.

Thanks Curt, much appreciated!

**Comment by sellmerfud** [comment]
Hi GameTime14,

You can use the command: **adjust exit after win**
This will toggle the value to false and the program will no longer exit after on side has reached its victory condition.

**Comment by GameTime14** [comment]
Thank you Curt.
