### ISSUE TITLE
Muslim Brotherhood doesn't permit Marker placement in same country twice

### ISSUE THREAD

**Issue by MrSkinny** [sellmerfud/awakening#7]
As worded, the card says: "Place 1 Reaction marker in Egypt and up to 2 more Reaction markers in any countries including Egypt." I interpret this as being allowed to place the 2 markers outside Egypt in the **same** country if you wish. But the interface requires 2 **different** countries are entered.

**Comment by sellmerfud** [comment]
Thanks for reporting this problem.

I have modified the askCountries() function so that it now optionally allows duplicate entries.
The Muslim Brotherhood event code now takes advantage of this.  Version 3.4 is available.
