### ISSUE TITLE
Wrong condition used in FundingModerateDecision method

### ISSUE THREAD

**Issue by VasilyTomilchik** [sellmerfud/awakening#9]
https://github.com/sellmerfud/awakening/blob/9a3b95a3556f727292df018d19afa4aa7ca88d3a/src/main/scala/awakening/JihadistBot.scala#L573-L577

Looks like there should be "Moderate" instead of "Tight" in the condition:
```game.fundingLevel == Tight```

**Comment by sellmerfud** [comment]
Thanks for reporting the problem.  It has been fixed and released in version 4.12
